name = "Cypherpunks Brasil"
avatar = "images/logo.png"
bio = "Saudações criptoanarquistas, cypherpunks e demais amigos da criptosfera."
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.
