name = "Cypherpunks Brasil"
homepage = "https://github.com/cypherpunksbr"
avatar = "images/logo-120x120.webp"
bio = "Nós somos tribos de mente e alma, não definidos por nação ou raça, mas apenas por pensamento e essência. Estamos por toda parte - e estamos aqui para ficar."
