name = "Cypherpunks Brasil"
avatar = "images/logo.png"
bio = "Nós somos tribos de mente e alma, não definidos por nação ou raça, mas apenas por pensamento e essência. Estamos por toda parte - e estamos aqui para ficar."
