baseURL = "https://cypherpunks.com.br/"
title = "Cypherpunks Brasil"
theme = "hugo-theme-bootstrap"
copyright = "(CC0) 2018-{year} Cypherpunks Brasil. O site está sobre a licença Creative Commons Zero, pode copiar!"

paginate = 10
# paginatePath = "page"

# Google analytics
# googleAnalytics = "UA-123-45"

googlefonts = ["Droid Sans", "Fira Mono"]
fontbody = 'Droid Sans'
fontcode = 'Fira Mono'

enableRobotsTXT = true

enableEmoji = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  author = "author"

[Date]
  Format = "2006-1-2"