baseURL = "https://cypherpunks.com.br"
title = "Cypherpunks Brasil"
theme = ["hugo-theme-bootstrap", "hugo-shortcode-gallery"]
copyright = "(CC0) 2018-{year} Cypherpunks Brasil. O site está sobre a licença Creative Commons Zero, pode copiar!"
languageCode = "pt-br"

paginate = 5
# paginatePath = "page"

googlefonts = ["Droid Sans", "Fira Mono"]
fontbody = 'Droid Sans'
fontcode = 'Fira Mono'

enableRobotsTXT = false

enableEmoji = true

markup.goldmark.renderer.unsafe = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  author = "author"

[Date]
  Format = "2006-1-2"

[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
  excludeFiles = ['**README.md', '**readme.md']
