[[main]]
  name = " Home"
  identifier = "home"
  pre = '<img class="logo" alt="Logo" src="http://localhost:1313/images/logo.png" loading="lazy" width="1087" height="1087">'
  url = "/"
  weight = 1

[[main]]
  name = " Ano"
  identifier = "archives"
  pre = "<i class='fas fa-fw fa-calendar-alt'></i>"
  url = "/arquivo"
  layout = "archive"
  weight = 2

#[[main]]
#  name = " Categoria"
#  identifier = "categories"
#  pre = "<i class='fas fa-fw fa-folder'></i>"
#  url = "/categorias"
#  weight = 5

[[main]]
  name = " Tag"
  identifier = "tags"
  pre = "<i class='fas fa-fw fa-tags'></i>"
  url = "/tags"
  weight = 4

[[main]]
  name = " Autor"
  identifier = "author"
  pre = "<i class='fas fa-fw fa-user'></i>"
  url = "/autores"
  weight = 3