github = "cypherpunksbr"
telegram = "CypherpunksBrasil"
odysee = "CypherpunksBrasil"
youtube = "CypherpunksBrasil"
instagram = "cypherpunksbrasil"
facebook = "cypherpunksbrasiloficial"
twitter = "cypherpunksbr"
